<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PublishAot>true</PublishAot>
    <StripSymbols>true</StripSymbols>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Amazon.Lambda.Core" Version="2.5.0" />
    <PackageReference Include="Amazon.Lambda.DynamoDBEvents" Version="3.1.1" />
    <PackageReference Include="Amazon.Lambda.RuntimeSupport" Version="1.11.0" />
    <PackageReference Include="Amazon.Lambda.Serialization.SystemTextJson" Version="2.4.4" />
    <PackageReference Include="AWSSDK.DynamoDBv2" Version="3.7.400.7" />
    <PackageReference Include="AWSSDK.Lambda" Version="3.7.400.7" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\VELoyalty.Core\VELoyalty.Core.csproj" />
    <ProjectReference Include="..\VELoyalty.Data\VELoyalty.Data.csproj" />
    <ProjectReference Include="..\VELoyalty.Notifications\VELoyalty.Notifications.csproj" />
  </ItemGroup>

</Project>
