<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsAotCompatible>true</IsAotCompatible>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AWSSDK.DynamoDBv2" Version="3.7.400.7" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\VELoyalty.Core\VELoyalty.Core.csproj" />
  </ItemGroup>

</Project>
